version: '2.1'

services:
  server:
    image: adrianvved/hudeem-backend
    ports:
      - 9092:9090
    depends_on:
      vitsql:
        condition: service_healthy
  vitsql:
    image: mysql:5.7.32
    ports:
      - 3307:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hudeem
    healthcheck:
      test: [ 'CMD', 'mysqladmin' ,'ping', '-h', 'localhost' ]
      timeout: 20s
      retries: 10